-- RentWise seed — neighborhood fallback.
-- AUTO-GENERATED by app/ml/prepare_real_data.py. Neighborhoods are now created
-- in seed_all.sql (geographic zones from real coordinates); this only fills in
-- any property left without a neighborhood. Run after seed_all.sql.

DO $$
BEGIN
  UPDATE properties p
  SET neighborhood_id = (SELECT n.id FROM neighborhoods n WHERE n.city_id = p.city_id LIMIT 1)
  WHERE p.neighborhood_id IS NULL;
END $$;
